;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="StateTree GoToNest",NewTagName="StateTree")
+GameplayTagList=(Tag="StateTree",DevComment="")
+GameplayTagList=(Tag="StateTree.Event",DevComment="")
+GameplayTagList=(Tag="StateTree.Event.EmergingDone",DevComment="")
+GameplayTagList=(Tag="StateTree.Event.PlayerJump",DevComment="")
+GameplayTagList=(Tag="StateTree.Event.RetractingDone",DevComment="")

